### PR TITLE
Added Halite III swag

### PR DESCRIPTION
**Pull request by FrankWhoee**
- [x] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  
Fill the corresponding section below:

(New Swag Proposal)  
Q. Have you received swag from this?  Yes
Q. How long did it take?  A week or two
Q. Does it ship worldwide?  Yes

(Something else)  
Please describe your changes here:

### CODE REVIEW

**Comment by swapagarwal** [comment]
@FrankWhoee What is that high rank?

**Comment by zac-garby** [comment]
What ever happened to that issue about putting ref urls in the PR description?

**Comment by plibither8** [comment]
I don't think competition prizes amount to "free swag". We should've added js13kgames if it did.

**Comment by swapagarwal** [comment]
@zac-garby Need to update the PR template. 😅
@plibither8 Agreed!

**Pull request closed without merging**
