### PR TITLE
Add mattermost

### PR DESCRIPTION
**Pull request by letsila**
Add mattermost.

### CODE REVIEW

**Comment by swapagarwal** [comment]
Is this still active?

**Comment by letsila** [comment]
Yep. Here is another reference https://docs.mattermost.com/developer/contribution-guide.html

**Comment by Razzeee** [comment]
I even got a security mug when i fixed a security feature.
Also got some coasters.
And also got a sweater, for working again on it.

**Comment by thekaleidoscope** [comment]
Why was this closed?

**Comment by swapagarwal** [comment]
I'm cleaning up all old issues and PRs which did not get much traction. The popular ones have already been merged. I'm focusing on getting a website ready before Hacktoberfest. 😇

**Pull request closed without merging**
