### PR TITLE
Removing digital ocean

### PR DESCRIPTION
**Pull request by juancri**
The survey has ended

### CODE REVIEW

**Comment by swapagarwal** [comment]
I was thinking if we should just move it to a separate section (expired) below instead of removing it completely. This would help in keeping a tab on the link when it becomes active again! What do you think?

**Comment by swapagarwal** [comment]
How about adding something like this?

**Comment by karanrajpal14** [comment]
@swapagarwal makes sense. Go for it! :+1:

**Comment by swapagarwal** [comment]
Thanks @juancri and @karanrajpal14! 👍

**Comment by vikaspotluri123** [comment]
You might want to add it to the ToC as well 🤔

**Comment by swapagarwal** [comment]
@vikaspotluri123 I added there first, but faced some problems in linking to the corresponding section. Working into it..

**Comment by swapagarwal** [comment]
Done! 🎉

**Pull request merged**
