### PR TITLE
Complete swag-for-dev community profile

### LINKED ISSUE #30: [Suggestion] Add code of conduct.
*No description provided.*

### PR DESCRIPTION
**Pull request by vikaspotluri123**
- Check off the remaining to-do items for our [community guidelines](https://github.com/swapagarwal/swag-for-dev/community)

- closes #30 

- This will probably require some discussion 🗣

### CODE REVIEW

**Comment by swapagarwal** [comment]
Thanks @vikaspotluri123! 👍

**Comment by swapagarwal** [comment]
CoC isn't checked here yet: https://github.com/swapagarwal/swag-for-dev/community
Maybe some naming issue?

**Comment by plibither8** [comment]
Maybe a cache issue &mdash; let's give it some time. Shouldn't be a naming issue because all other repos too have `CODE_OF_CONDUCT.md` as the filename.

**Comment by swapagarwal** [comment]
I don't think it's a cache issue; `Contributing` got reflected pretty instantaneously.

**Pull request merged**
