### PR TITLE
Add Mullvad

### PR DESCRIPTION
**Pull request by marci010101**

### CODE REVIEW

**Comment by marci010101** [comment]
@rbstrachan Thanks, I updated it!

**Comment by avijit1998** [comment]
I wanted to ask if  Mullvard sends the sticker free to other countries. I mean to include all the money involved including the probable custom charges or shipping charges...

**Comment by marci010101** [comment]
@avijit1998 I don't know, to tell the truth, I haven't requested one from them yet, just heard about them, you should contact them on **support@mullvad.net**.

**Comment by bbbenji** [comment]
Took about 3 days not counting the weekend to get my stickers.

**Comment by vintagesucks** [comment]
Took 5 business days to get mine (Germany).

**Comment by linakis** [comment]
5 days (Greece)

**Comment by kevin51jiang** [comment]
Received. Forget how long, probably around 1 week. Canada.

**Comment by VickieSullivan** [comment]
Works like a charm 💎

**Comment by swapagarwal** [comment]
Thanks @marci010101 for taking the time to add this! 👍 
Thanks @rbstrachan for reviewing the changes. 🎉 
Kudos to all folks who verified it! 💯

**Pull request merged**
