### PR TITLE
Add Setapp swag

### PR DESCRIPTION
**Pull request by ivira**
Hello,

Here is information about swag (stickers and MacBook) from Setapp team for completing survey. Thanks.

### CODE REVIEW

**Comment by mc388** [comment]
I completed the survey but I don't know how to get the swag

**Comment by kevin51jiang** [comment]
Same, it didn't ask for an address and I didn't get an email asking for it.

**Comment by ivira** [comment]
@mc388 We will send all swags on May 1, when the survey is end.

@kevin51jiang Hmmmm, the last question of a survey is an email request. There is seems to be no way to finish survey without answering to it. Could you please try again.

**Comment by mc388** [comment]
I just entered my email address but no shipping address. And I also got no confirmation email

**Comment by ivira** [comment]
@mc388 yeah, currently we don't send confirmation letters. We'll send all of them in bulk on May 1.

**Comment by mc388** [comment]
@ivira ok thank you, so I will wait a few days

**Comment by avijit1998** [comment]
I did not find the link. And is it international.

**Comment by ivira** [comment]
@avijit1998 yes, it's international. Link to survey https://www.surveymonkey.com/r/R2ZSKMF Please consider that it's only for Mac Developers.

**Comment by kevin51jiang** [comment]
@ivira OK seems like I got the email asking for an address now

**Comment by cozyplanes** [comment]
@ivira Is it still valid? I finished the survey, typed my email, but got no email asking for address. Also, is the promotion only macbook? Is there stickers as well? Thanks

**Comment by ivira** [comment]
Closing this PR as survey is over today and swag is not available. Thanks everyone participated 🤗

**Comment by cozyplanes** [comment]
@ivira  i participated before the deadline. Will the swag be sent?? Thanks

**Comment by ivira** [comment]
@cozyplanes yes, everyone who participated will get a swag.

**Comment by 4doge** [comment]
@ivira hope you're doing well. It's june now. How is going with sending swag?

**Comment by ivira** [comment]
@cozyplanes @4doge hi! Good news, all the swag have been already sent. Wait for some more time, delivery time from Ukraine can be a bit long. Thanks.

**Comment by cozyplanes** [comment]
@ivira That's awesome to hear. Thanks!

**Comment by dopsy** [comment]
received the swag today in Europe. Thanks!

**Comment by cozyplanes** [comment]
Got it today, thanks!

**Comment by techytushar** [comment]
i received the swags today, thanks @ivira

**Comment by marci010101** [comment]
Received it today, not just stickers but a t-shirt, too! :D

**Comment by NaveenDA** [comment]
I got T-shirt and Sticker today. thanks @ivira

**Comment by tonyvince** [comment]
Received T-shirt and stickers in India. Thanks @ivira

**Comment by kb-studios** [comment]
Received the swag in India! The best I have had so far! 🍕

**Comment by swapagarwal** [comment]
Thanks @ivira! 👍

**Comment by danimart1991** [comment]
Seems it not available anymore.

**Comment by cozyplanes** [comment]
@danimart1991 thats why it is closed

**Pull request closed without merging**
