### PR TITLE
Add Microsoft Office Swag

### PR DESCRIPTION
**Pull request by AlbertusCraddle**

### CODE REVIEW

**Comment by HammyHavoc** [comment]
I emailed the address mentioned on that page and the email was returned; issue at Microsoft's end. Is this still a promo that's active?

**Comment by AlbertusCraddle** [comment]
I think it is still active but my e-mail was rejected too. 🤔
@jthake & @richdizz, what do you think?

**Comment by ApolloZhu** [comment]
https://twitter.com/search?q=%23Office365Dev%20%23Swag

Most likely this ended in 2015.

**Comment by swapagarwal** [comment]
Feel free to reopen if it becomes active again! 😅

**Pull request closed without merging**
