### PR TITLE
Add "Date added" as a sorting method

### PR DESCRIPTION
**Pull request by plibither8**
A simple addition to the sorting selection. Items can now be sorted in `Date added` and `Date added, reversed` order.

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
Wording should be updated to `newest|oldest first` to be less ambiguous

Also, as we're adding more filtering options, any thoughts on having only ascending sort functions, and descending logic is just reversing the result of ascending? It will probably be a minor performance hit (of n) but would make the code a bit more DRY 🤔

**Comment by plibither8** [comment]
Just to be clear, you're suggesting to remove descending / reversed altogether, right?

**Comment by vikaspotluri123** [comment]
Nope, just update the logic

`sortMethods.alpha().reverse()` => alphabetical reverse

**Comment by plibither8** [comment]
Oh, okay. Where exactly though? In the `handleSort()` function?

**Comment by vikaspotluri123** [comment]
Yep

**Comment by swapagarwal** [comment]
`LGTM!`
@plibither8 Can you rebase and merge it? 😇

**Comment by plibither8** [comment]
Hi! I've rebased it and fixed the merge conflicts the best I could. The deploy previews look good and I've tested it. Merging! :smile:

**Comment by swapagarwal** [comment]
Thanks! 🤗

**Pull request merged**
