### PR TITLE
Fixed border on swag images

### PR DESCRIPTION
**Pull request by sanjpareek**
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

Changes are for issue #412. As per description mentioned on the issue, I have changed the CSS to show borders under anchor tags only when they are hovered upon..not on hover of item.

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
I think the text should always be underlined

https://5d991e2a926d650008cec435--peaceful-chandrasekhar-efde8e.netlify.com/

**Comment by sanjpareek** [comment]
@vikaspotluri123 Can you please review the fix? I have made new changes. Thanks.

**Comment by vikaspotluri123** [comment]
I don't think the image should be underlined when hovered /cc @aslafy-z

**Comment by aslafy-z** [comment]
Correct, see netlify preview link above.

**Comment by sanjpareek** [comment]
Ok, that's done. Please have a look. Thanks.

**Pull request merged**
