### PR TITLE
Add added date for each swag item

### PR DESCRIPTION
**Pull request by aslafy-z**
- [x] I've checked that this isn't a duplicate pull request.

Add added date in ISO format.

Needed for #160

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
Refs #160?

**Comment by aslafy-z** [comment]
Nice! Need another approval before any other swag is added (please :D).

**Comment by aslafy-z** [comment]
Does `dateAdded` tag fits you guys?

**Comment by swapagarwal** [comment]
@aslafy-z How are we backfilling the data?

**Comment by aslafy-z** [comment]
I used the issues / PR creation date as reference for existing items, you mean for next items?

**Comment by swapagarwal** [comment]
The ideal way would be to use the merged timestamp in future, what do you think?

**Comment by swapagarwal** [comment]
Thanks @aslafy-z! 🚀

**Pull request merged**
