### PR TITLE
Added swag opportunity for loftlabs

### PR DESCRIPTION
**Pull request by sarojregmi200**
Fixes: #1129
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

### CODE REVIEW

**Comment by aslafy-z** [comment]
Please review the CI results

**Comment by sarojregmi200** [comment]
@aslafy-z I should have accounted for those errors earlier, anyways I am here going for a very important festival of our Dashain. Happy Dashain to all. I will be right back to the issues. It will take almost 1 week at most. 
If it's too long then I suggest this issues of mine to be reassigned to @aashishpanthi @utsavbhattarai007 or https://github.com/rajeshkhadka200.

Anyways it will not make it to that point.
Sorry for inconvenience, Hope you understand.
I am running late for my ride.
See y'all.

**Comment by aashishpanthi** [comment]
Passed all CI tests. Please merge the changes

**Comment by aslafy-z** [comment]
Fixes #1167

**Pull request closed without merging**
