### PR TITLE
Implement Image lazyloading

### PR DESCRIPTION
**Pull request by aslafy-z**
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

Native lazy loading will come in future versions of web browsers: https://css-tricks.com/a-native-lazy-load-for-the-web-platform/

Since then, I included the https://github.com/ApoorvSaxena/lozad.js module, the most tiniest and up to date module I found. It has no dependencies, <1k, and pretty fast.

I used this image as a placeholder, feel free to propose another (it could be the logo when we have one): https://loading.io/spinner/heart/-beating-heart-preloader

spinner

Once it's merged, we can add [devSwag](https://devswag.io) to lozad users list:
https://github.com/ApoorvSaxena/lozad.js/#more-than-3000-sites-are-using-lozadjs-heres-few-of-them

### CODE REVIEW

**Comment by plibither8** [comment]
Instead of showing nothing to those users that have disabled JS, let's disable lazyloading? At least the users will be able to see the content.

**Comment by aslafy-z** [comment]
@plibither8 Fixed! I forgot to add the logic to support that case :sweat_smile:

**Comment by aslafy-z** [comment]
[`lozad`](https://github.com/ApoorvSaxena/lozad.js/) **does** load images on-the-fly to decrease wasted bandwidth using intersection observer. Gonna do some more benches tomorrow, but I think it worth the load of the library.

**Comment by vikaspotluri123** [comment]
It might be running it too early because I only see beating hearts once

I need more beating hearts! 😝

**Comment by aslafy-z** [comment]
I guess it's too early for `loading` attr :(
https://caniuse.com/#feat=loading-lazy-attr

**Comment by aslafy-z** [comment]
#587 does this.

**Pull request closed without merging**
