### PR TITLE
Add elastic swag !

### PR DESCRIPTION
**Pull request by artonge**

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Is there a link to the actual promotion?

**Comment by artonge** [comment]
I can't find any talking about the t-shirt. I just received a mail after completing the [free trial](https://www.elastic.co/cloud/as-a-service/signup).

**Comment by cozyplanes** [comment]
@artonge what email from who did you got? and is it still valid?

**Comment by artonge** [comment]
I received it from ecloud@elastic.co.
I think it is still valid.

**Comment by cozyplanes** [comment]
@artonge got it as well, thanks
Still valid at the time i am writing this comment

**Comment by MartinHennrich** [comment]
When did you receive the mail with the survey? My trial ended last week and I still did not receive such a mail.  🤔

**Comment by artonge** [comment]
Soon after the end of the trial. It's weird that they don't give further information.

**Comment by cozyplanes** [comment]
Send an email to ecloud@elastic.co politely requesting a tshirt, and have finished the trial @MartinHennrich @artonge

**Comment by MartinHennrich** [comment]
Unfortunately, Elastic does **not** send out shirts anymore. If you are interested, please head to [https://elastic.shop/](https://elastic.shop/) or attend the Elastic{ON} user conference.

**Pull request closed without merging**
