### PR TITLE
Exposed dataset on website

### PR DESCRIPTION
**Pull request by ARKEOLOGIST**
- [X] I've checked that this isn't a new swag opportunity proposal.
- [X] I've checked that this isn't a duplicate pull request.

Made a few minor changes to fix https://github.com/swapagarwal/swag-for-dev/issues/534
The dataset can now be viewed on-site through the "view data" hyperlink at the bottom of the page.

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
The link to `data.json` doesn't seem to work 🤔 I think you might need to copy it to the `dist` directory as part of the build

**Comment by ARKEOLOGIST** [comment]
Sorry for that, I forgot to commit my changes.

**Comment by ARKEOLOGIST** [comment]
Any updates on this?

**Comment by aslafy-z** [comment]
Hello! Thanks for the change, Ithink we should enable CORS for that file. Can you please lint your code, as you can see the lint pipeline is failing. Thank you!

**Comment by ARKEOLOGIST** [comment]
Hello, I have fixed the lint issues. The unit tests failing (and error in deployment) are due to an error in one of the URLs, which seems to be failing for some reason. (returning code 401).

**Comment by ARKEOLOGIST** [comment]
Hello, please have a look at the changes and tell me if anything more is needed, thanks.

**Pull request closed without merging**
