### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Kaushal-brahmbhatt**
- [ ] I've checked that this isn't a new swag opportunity proposal.
- [ ] I've checked that this isn't a duplicate pull request.

### CODE REVIEW

**Comment by Kaushal-brahmbhatt** [comment]
> * [ ]  I've checked that this isn't a new swag opportunity proposal.
> * [ ]  I've checked that this isn't a duplicate pull request.

IT'S for hactoberfest

**Comment by Kaushal-brahmbhatt** [comment]
> > * [ ]   I've checked that this isn't a new swag opportunity proposal.
> > * [ ]   I've checked that this isn't a duplicate pull request.
> 
> IT'S for hactoberfest

request to accept it as soon as possible please

**Comment by vikaspotluri123** [comment]
Sorry @Kaushal-brahmbhatt, but this is not a meaningful PR. There are almost 50 issues to solve in this repo, feel free to ask to be assigned to one of those.

**Comment by Kaushal-brahmbhatt** [comment]
yes please assign

**Pull request closed without merging**
