### PR TITLE
docs: Grammatical updates to README.md

### PR DESCRIPTION
**Pull request by isha-narula**
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

There were some grammatical errors in README.ms file.I have attached the screenshot below!
Screenshot from 2020-08-05 12-10-12

### CODE REVIEW

**Comment by isha-narula** [comment]
Hey! I am a noob in open source community! I have made some changes in README.md file.Please review it

**Comment by isha-narula** [comment]
Hey! I am a noob in open source community! I have made some changes in README.md file.Please review it

**Comment by aslafy-z** [comment]
@swapagarwal @vikaspotluri123 all good to you?

**Comment by swapagarwal** [comment]
LGTM!

**Review by vikaspotluri123 — APPROVED** [review]

**Pull request merged**
