### PR TITLE
✨Add Netlify Configuration

### PR DESCRIPTION
**Pull request by vikaspotluri123**
- [x] I've checked that this isn't a duplicate pull request.

Please describe your changes here:
 - Add Netlify build configuration
   - Configures Netlify to use `site` as the root and `site/dist` for publishing
 - Add basic headers
  - Mostly security / cache related

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
https://securityheaders.com/?q=https%3A%2F%2F5bb59f4c3813f05385baf32b--peaceful-chandrasekhar-efde8e.netlify.com%2F&followRedirects=on 😎 

I didn't add CSP since that requires setting up ReportURI or a similar service

**Comment by aslafy-z** [comment]
Maybe you could add caching for /assets/img

**Comment by aslafy-z** [comment]
Also CSP's report-uri has been deprecated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri

**Comment by aslafy-z** [comment]
It would be great to add a Link header:

```
# COMMENT: Multi-key header rules are expressed with multi line strings
Link = ''' </assets/style.css>; rel=preload; as=stylesheet, \
</assets/js/site.js>; rel=preload; as=script, \
</Assets/img/logo.png>; rel=preload; as=image'''
# Headers for H2 Server Push 
```

**Comment by swapagarwal** [comment]
Hey Vikas, thanks for taking this initiative!
I see that you have specified a cache-time of around 2 years for static assets. Can you share the reasoning behind it?

**Comment by vikaspotluri123** [comment]
> I see that you have specified a cache-time of around 2 years for static assets. Can you share the reasoning behind it?

I wrote these headers for a different project and ported it here. About 10 minutes ago it hit me that this header is currently a terrible idea because there's no cachebusting (the process where you hash the contents of a file and add it to the filename) which means when a new version of the site is released, returning visitors won't know 🙈 


> It would be great to add a Link header to take advantage of HTTP/2 offered by Netlify:

Based on what I said earlier, I'll reimplement it. In the other project, I was having issues with caching but since caching should be short for the css + js (at least until cachebusting is possibly implemented) that's a nonissue here

> Maybe you could add caching for /assets/img

I concur, will work in that as well!

**Comment by vikaspotluri123** [comment]
> I concur, will work in that as well!

Circling back, this faces the same issue as the scripts 'n styles, which are currently completely unoptimized 🤔

**Comment by vikaspotluri123** [comment]
> Could you please elaborate ? Unoptimized for caching or what ? I don't get it, sorry.

Unoptimized for caching in that you still have the cachebusting issues. Since #59 hasn't been merged the non-ideal images will sit in users' browser cache. It's not gonna make the world explode, but I don't like putting unneeded perf burden on the client 🤷‍♂️

**Comment by vikaspotluri123** [comment]
Preloading has been added ⚡️

**Comment by vikaspotluri123** [comment]
@swapagarwal let me know if there's anything you feel is missing for the initial implementation

**Comment by swapagarwal** [comment]
Looks good for the initial implementation; TODO caching (mainly for images).

**Comment by swapagarwal** [comment]
Thanks @vikaspotluri123! 👍

**Pull request merged**
