### PR TITLE
Add Auth0 Hacktoberfest 

### PR DESCRIPTION
**Pull request by mcgrathg**
- ✅  I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  New
Fill the corresponding section below:

(New Swag Proposal)  
Q. Have you received swag from this?  No
Q. How long did it take?  Unknown
Q. Does it ship worldwide?  Unknown

(Something else)  
Please describe your changes here: 
Added Auth0's Hacktoberfest 2018 information

### CODE REVIEW

**Comment by swapagarwal** [comment]
@mcgrathg Can you find a placeholder image to add here?

**Comment by swapagarwal** [comment]
Agreed, that's why I mentioned placeholder. devswag.io needs an image in each item. See microsoft image for an example.

**Comment by mcgrathg** [comment]
I'll add a generic t-shirt and sticker placeholder tomorrow. 

Should I use the same shirt as the Microsoft one?

**Comment by sdushantha** [comment]
Here is an image of their swag

**Comment by mcgrathg** [comment]
@sdushantha I think that's the https://hacktoberfest.digitalocean.com/ t-shirt, not Auth0's.

**Comment by sdushantha** [comment]
@mcgrathg Sorry my bad. I was kinda confused from the title. I thought Hacktoberfest was just a Digital Ocean and GitHub thing

**Comment by kevin51jiang** [comment]
What about [this image?](https://cdn.auth0.com/blog/hacktoberfest:logo.png0)

**Comment by mcgrathg** [comment]
@kevin51jiang No, that's an image from DigitalOcean/GitHub/twillio.

**Comment by mcgrathg** [comment]
I created a new generic t-shirt and sticker image for auth0 as a placeholder.

It combines the [blank shirt](https://images.all-free-download.com/images/graphiclarge/blank_t_shirt_clip_art_19042.jpg) temporarily being using for Microsoft and a [blank sticker](https://ubisafe.org/images/blanking-clipart-sticky-label.jpg)

**Comment by hugovk** [comment]
This branch has conflicts that must be resolved.

**Comment by swapagarwal** [comment]
Thanks @mcgrathg! 👍

**Pull request merged**
