### PR TITLE
add-TensorFlow-swag

### PR DESCRIPTION
**Pull request by nadasuhailAyesh12**
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

### CODE REVIEW

**Comment by aslafy-z** [comment]
Hello, can you please update the reference link to a page that explains how it works ? Is it free ?

**Comment by nadasuhailAyesh12** [comment]
Absolutely, I'll update the reference URL to guide contributors on how to contribute to TensorFlow. Once they've made their contribution, they can communicate with the TensorFlow team to select their free swag. Before I proceed, could you please confirm if the suggested reference URL meets your expectations for an immediate update?

**Comment by aslafy-z** [comment]
>  Once they've made their contribution, they can communicate with the TensorFlow team to select their free swag. 

This offer is typically verified through a link to a blog post. How did you come across this promotion?

**Comment by nadasuhailAyesh12** [comment]
> > Once they've made their contribution, they can communicate with the TensorFlow team to select their free swag.
> 
> This offer is typically verified through a link to a blog post. How did you come across this promotion?
I came across this promotion through a Twitter post that outlined the process of receiving swag after making a contribution.
This is the link of the post  https://twitter.com/tensorflow/status/1378075067729334272,there are other posts at LinkedIn

**Comment by aslafy-z** [comment]
Pease follow the link, you'll see they are not accepting new entries. I'll go ahead and close this PR, feel free to reopen it if the opportunity comes back to life! Thank you @nadasuhailAyesh12

**Pull request closed without merging**
