### PR TITLE
Added Netlify Sticker Swag

### PR DESCRIPTION
**Pull request by austriker27**
- [x] I've checked that there isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  

New Swag Proposal
Q. Have you received swag from this?
Not yet
Q. How long did it take?
N/A
Q. Does it ship worldwide?
I think so?

Please describe your changes here: 
Adding Netlify sticker swag!

### CODE REVIEW

**Comment by ragasirtahk** [comment]
Netlify do sends swag. It took two weeks to ship to my place in India. However, I didn't use the link (http://swag.netlify.com/docs/) to order swag, I received it when I reported a bug in their website.

**Comment by tonyvince** [comment]
I received netlify swag

**Comment by kevin51jiang** [comment]
Yep,  I just got it a few days ago too.

**Comment by cozyplanes** [comment]
Got it

**Comment by swapagarwal** [comment]
Thanks @austriker27! 👍 
Kudos to everyone for confirming. 😇

**Pull request merged**
