### PR TITLE
Adding Google Cloud Opportunity

### PR DESCRIPTION
**Pull request by Xtremilicious**
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

Adding Google Cloud Study Jam 2019 Opportunity

### CODE REVIEW

**Comment by aslafy-z** [comment]
Well, as it ships only to india, I'm not sure whether we should add this or not. 

We could eventually tag this swag with some label and then filter on it. WDYT @vikaspotluri123 @swapagarwal @plibither8 ?

**Comment by Yash-Garg** [comment]
@aslafy-z August one has ended and they haven't started September registrations yet. So i suggest to wait until they open September registrations

**Comment by Xtremilicious** [comment]
As @Yash-Garg said, if and when September registrations start, it needs to be updated.
As for the India-only-shipping issue, whether to post this or not, depends on other collaborators:)

**Comment by vikaspotluri123** [comment]
Codeship has limited shipping and we've allowed it, so I see no issue with allowing this as well. If the challenge is recurring, I think we should include that in the description and allow the community to submit the updated link, if it changes.

**Comment by swapagarwal** [comment]
This hasn't been updated for September, so closing. These type of items are best shared in the Telegram group! 😉

**Pull request closed without merging**
