### PR TITLE
Update data.json

### PR DESCRIPTION
**Pull request by berry120**
Hacktoberfest was in the stickers category - it's just a t-shirt AFAIK, so that should be removed.

- [x] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  
Fill the corresponding section below:

(New Swag Proposal)  
Q. Have you received swag from this?  
Q. How long did it take?  
Q. Does it ship worldwide?  

(Something else)  
Please describe your changes here: 

Fix to data.json

### CODE REVIEW

**Comment by swapagarwal** [comment]
IIRC, they used to ship stickers too!
Folks, does someone have more information on this?

**Comment by berry120** [comment]
Ah feel free to kill it if I'm wrong - somehow Hacktoberfest has evaded me until this year, so I've no idea...

**Comment by plibither8** [comment]
The [website](https://hacktoberfest.digitalocean.com/details) only mentions T-shirts, no mention of stickers anywhere

**Comment by berry120** [comment]
Ah, burn it. My mistake.

https://hacktoberfest.digitalocean.com/faq

"How do I get stickers?
Stickers are included with your t-shirt, once you complete 5 PRs."

**Comment by swapagarwal** [comment]
Haha, no issues! Happens to the best of us.
All the best for Hacktoberfest! And keep an eye on devswag.io 😉

**Pull request closed without merging**
