### PR TITLE
fix issue #94

### PR DESCRIPTION
**Pull request by greybax**
- [x] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  no
  
Please describe your changes here: 
This is fix for issue #94

### CODE REVIEW

**Comment by swapagarwal** [comment]
@greybax Are you sure it's the right issue?

**Comment by greybax** [comment]
@swapagarwal oohh, sorry, seems that I've wrong marked the issue which I've fixed. Of course it should be issue #94

**Comment by greybax** [comment]
@vikaspotluri123 yeah, seems its better solution. Will fix it now.

**Comment by vikaspotluri123** [comment]
You can just chain to the initial logic

```js
const tags = Array.from(builtSwagList.reduce(
        (tagList, { tags }) => {
            tags.forEach(tag => tagList.add(tag));
            return tagList;
        },
        new Set()
    )).sort();
```

**Comment by swapagarwal** [comment]
Thanks @greybax and @vikaspotluri123! 👍

**Pull request merged**
