### PR TITLE
Removing this entry as Hacktoberfest 2018 is over and the offering has ended

### PR DESCRIPTION
**Pull request by nul800sebastiaan**
- [x] I've checked that this isn't a duplicate pull request.

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
Hey there 👋 Thanks for your PR!

Rather than getting a new PR for _every_ hacktoberfest-related opportunity, could you remove the rest of the swag in this PR and place them in a new file (e.g. `data-expired.json`)? There are plans (#153) to have better tracking of expired opportunities in the future 😄 

/cc @swapagarwal @aslafy-z

**Comment by swapagarwal** [comment]
Agree with Vikas here.
Let's not remove the data; just add a key denoting that the opportunity has expired. 


---- On Thu, 01 Nov 2018 18:15:12 +0530 notifications@github.com wrote ----



Hey there 👋 Thanks for your PR!

Rather than getting a new PR for every hacktoberfest-related opportunity, could you remove the rest of the swag in this PR and place them in a new file (e.g. data-expired.json)? There are plans (#153) to have better tracking of expired opportunities in the future 😄

/cc @swapagarwal @aslafy-z

**Comment by aslafy-z** [comment]
Follow the discussion here: https://github.com/swapagarwal/swag-for-dev/issues/88
Closing this, thanks anyway @nul800sebastiaan.

**Comment by vikaspotluri123** [comment]
This was done in #156, thanks though!

**Pull request closed without merging**
