### PR TITLE
Add Microsoft Hacktoberfest t-shirt

### PR DESCRIPTION
**Pull request by berry120**
2018's Hacktoberfest has the opportunity to gain a T-shirt from Microsoft as well as the normal one from Github / DigitalOcean.

- [x] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  
Fill the corresponding section below:

(New Swag Proposal)  
Q. Have you received swag from this?  Not yet, as the event is brand new - but Microsoft should be a pretty reliable source.
Q. How long did it take?  N/A
Q. Does it ship worldwide?  N/A

(Something else)  
Please describe your changes here:

### CODE REVIEW

**Comment by swapagarwal** [comment]
Makes sense.

**Comment by swapagarwal** [comment]
@berry120 Can you find a placeholder image to add here until the t-shirt design is released?

**Comment by berry120** [comment]
No problem, that's now added.

**Comment by swapagarwal** [comment]
Last thing: We just launched a website a couple of hours ago!
It'd be great if you can update `data.json` as well (used for building website).

**Comment by berry120** [comment]
No problem, done.

**Comment by swapagarwal** [comment]
Thanks @berry120! 👍

**Pull request merged**
