### PR TITLE
Image generation bug gulp

### PR DESCRIPTION
**Pull request by ajitsinghkaler**
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

Images were first made responsive according to height but according to the CSS applied we have to set it according to the width. Which is what I've done I've set it according to width.

### CODE REVIEW

**Comment by aslafy-z** [comment]
Thank you @ajitsinghkaler! 
I'm not sure it will fit the redesign done by @anhek in #443. Can you have a look?

**Comment by ajitsinghkaler** [comment]
Yeah, it will look really bad, so what can we do with images which don't fit into our aspect ratio should I enlarge them or what because cramping existing images into that section is not working. need your suggestion on this.


Desktop screenshot (12)

**Comment by ajitsinghkaler** [comment]
So for that, we have to make no changes and we can keep our code as it is and close issue number #447

**Comment by ajitsinghkaler** [comment]
but then again the third image is cut down because this has it is not at a specific aspect ratio.

**Comment by ajitsinghkaler** [comment]
Cn you please look into this

**Comment by ajitsinghkaler** [comment]
@swapagarwal @aslafy-z @vikaspotluri123 Can you please tell me what I should do with this

**Pull request closed without merging**
