### PR TITLE
Multiple issue & pull-request templates

### PR DESCRIPTION
**Pull request by aslafy-z**
- [x] I've checked that this isn't a duplicate pull request.

I just discovered we are able to use multiples issue and pull-request templates, the UI will just ask you wich one you want to use.
Example: https://github.com/aslafy-z/swag-for-dev/issues => New issue goes to https://github.com/aslafy-z/swag-for-dev/issues/new/choose

Github reference: 
https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/

**Edit**: It doesn't works pretty well with pull-requests: There is no UI to select which template to use. Alternatively, we could add a link to the readme who points to this: https://github.com/aslafy-z/swag-for-dev/compare/master...aslafy-z:add-hasura?expand=1&template=new-swag-opportunity.md

### CODE REVIEW

**Comment by swapagarwal** [comment]
Good idea!

**Comment by swapagarwal** [comment]
I went to https://github.com/aslafy-z/swag-for-dev/issues and clicked on new issue -> Did not get an option to choose a template.. 🤔

**Comment by swapagarwal** [comment]
Hmm.. Makes sense!
@aslafy-z Can you `cherry-pick` this commit on your `master` branch?

**Comment by aslafy-z** [comment]
@swapagarwal Done ;) see here: https://github.com/aslafy-z/swag-for-dev/issues/new/choose

**Comment by plibither8** [comment]
Looks good! There should be a third issue template too IMO, which caters to bugs in the website or feature requests. Basically, any issues regarding the website.

**Comment by swapagarwal** [comment]
@aslafy-z This looks awesome!
👍 on adding two more types: website and something else / others.

**Comment by vikaspotluri123** [comment]
Emojis are supported as well! [example](https://github.com/TryGhost/Ghost/blob/master/.github/ISSUE_TEMPLATE/--anything-else.md)

**Comment by vikaspotluri123** [comment]
Could you rebase to fix the issues with Netlify?

**Comment by aslafy-z** [comment]
Just did it @vikaspotluri123

**Comment by aslafy-z** [comment]
I just found out there where an UI to update these templates: https://github.com/aslafy-z/swag-for-dev/issues/templates/edit

**Comment by aslafy-z** [comment]
it looks great!

https://github.com/swapagarwal/swag-for-dev/issues/new/choose

2018-11-19-170445_1127x656_scrot

**Pull request merged**
