### PR TITLE
Add MS Ignite

### LINKED ISSUE #712: MS Ignite Cloud
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. :  Microsoft

Q. Where have you seen the announcement (URL)?  
A. :  https://csc.docs.microsoft.com/ignite/registration 

Q. What kind of swag (clothing, stickers, ...)?  
A. :  Earn a free Microsoft Certification exam and chances to win more prizes

Q. Have you received swag from this?  
A. :  Yes 

Q. How long did it take?  
A. :  One or more days

Q. Does it ship worldwide?  
A. :  Yes

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

### PR DESCRIPTION
**Pull request by will-chow**
closes #712 

- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

Added Microsoft Ignite Cloud Skills Challenge
Earn a free Microsoft Certification exam and chances to win more prizes

### CODE REVIEW

**Comment by will-chow** [comment]
How can I help fix the failing check?

**Comment by aslafy-z** [comment]
@will-chow you need to add an image to the entry

**Comment by will-chow** [comment]
Thanks for the pointer, please merge if good.

**Comment by achaljhawar** [comment]
@will-chow this opportunity has expired so pls close the PR

**Comment by vikaspotluri123** [comment]
Thanks @achaljhawar, closing

**Pull request closed without merging**
