### PR TITLE
Fix Website layout broken on mobile devices

### PR DESCRIPTION
**Pull request by danimart1991**
- [X] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  
Fill the corresponding section below:

(Something else)  
Please describe your changes here: 
Fix Website layout broken on mobile devices #82

### CODE REVIEW

**Comment by aslafy-z** [comment]
The screen size emulator is working like a charm. You can also hook your chrome desktop's developer tools to your Android phone running a chrome webpage, with ADB
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
. But it's not needed for this case.

**Comment by vikaspotluri123** [comment]
> @ danimart1991 How do I test this? 😇

Other testers can visit the preview URL (https://deploy-preview-83--peaceful-chandrasekhar-efde8e.netlify.com/) and compare it to the current version of the site (https://devswag.io) to ensure the bug is fixed

**Comment by aslafy-z** [comment]
Try this: http://diffee.me/?https://devswag.io?https://deploy-preview-83--peaceful-chandrasekhar-efde8e.netlify.com

**Comment by aslafy-z** [comment]
Try this, it's great ! http://diffee.me/?https://devswag.io?https://deploy-preview-83--peaceful-chandrasekhar-efde8e.netlify.com

**Comment by danimart1991** [comment]
It seems it's fixed with this PR.

**Comment by aslafy-z** [comment]
It does not look good on my phone: 
screenshot_20181005-113535

Reference:
Honor 9
1920*1080
Android 8.0 
Chrome 69

**Comment by danimart1991** [comment]
Update PR solving @aslafy-z issue.

**Comment by plibither8** [comment]
@swapagarwal Looks good to me! Let's merge 👍

**Comment by swapagarwal** [comment]
@plibither8 Awesome! Go ahead.. 😇

**Comment by swapagarwal** [comment]
Thanks @danimart1991! 👍

**Pull request merged**
