### PR TITLE
Add Gatsby

### PR DESCRIPTION
**Pull request by rscott**
- ✅ I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  **New**
Fill the corresponding section below:

(New Swag Proposal)  
Q. Have you received swag from this?  **No**
Q. How long did it take?  **Unknown**
Q. Does it ship worldwide?  **Yes**

(Something else)  
Please describe your changes here: Add Gatsby

### CODE REVIEW

**Comment by cozyplanes** [comment]
1. will receive soon
2. up to 6 weeks for int'l
3. yes

**Comment by 12vanblart** [comment]
1. Have you received swag? **Yes**
2. How long did it take? **4 days (US)**
3. Does it ship worldwide? **Yes**

**Comment by aslafy-z** [comment]
@rscott could rebase this and fix conflicts?

**Comment by aslafy-z** [comment]
Thanks @rscott!

**Pull request merged**
