### PR TITLE
Added SendGrid swag

### PR DESCRIPTION
**Pull request by emiliano-carrillo**
- [x] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  yes
(New Swag Proposal)  
Q. Have you received swag from this?  no
Q. How long did it take?  unknown
Q. Does it ship worldwide?  unknown

### CODE REVIEW

**Comment by swapagarwal** [comment]
It'd be great if you can update `data.json` as well (used for building website).

**Comment by emiliano-carrillo** [comment]
on my way!

**Comment by aslafy-z** [comment]
@emiliano-carrillo Could you please send your data.json diff here as the event already started ?
We need to merge this fast !

**Comment by swapagarwal** [comment]
Ping.

**Pull request closed without merging**
