### PR TITLE
Add Vultr swag

### LINKED ISSUE #178: Add Vultr swag
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate issue.

Q. Which company offers it?  
A. : [Vultr](https://www.vultr.com/)

Q. Where have you seen the announcement (URL)?  
A. : https://www.vultr.com/swag/

Q. What kind of swag (clothing, stickers, ...)?  
A. : stickers

Q. Have you received swag from this?  
A. : No

Q. Does it ship worldwide?  
A. : Yes

Requirements:
- Have to create an account before completing the form

- [x] I've checked that the promotion is legit.
- [x] I've checked that it's still available to the public.

### PR DESCRIPTION
**Pull request by aslafy-z**
## Wild swag opportunity appeared!

- [x] I've checked that this isn't a duplicate pull request.
- [x] I've checked that this is linked to a new swag opportunity issue <!>

Implement swag opportunity: Vultr

Closes #178

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
We just have to wait for some confirmation! /cc @swapagarwal do we have an official process in place for this?

**Comment by swapagarwal** [comment]
The official process is to get feedback from some of the folks who received it before merging. We couldn't do that in Hacktoberfest because of time-sensitivity but we should definitely do that going forward to maintain the quality. What do you think?

**Comment by vikaspotluri123** [comment]
That sounds good, but do we want to have an auto-approval process for bigger, well-known companies? There's no guarantee the bigger companies will maintain the quality, but we can have a reasonable expectation 🤔

**Comment by swapagarwal** [comment]
Agreed. @aslafy-z made a similar point and proposed that we contact them via Twitter or something and merge after confirmation.

**Comment by cozyplanes** [comment]
@swapagarwal this company was mentioned when this repo was first created, i submitted an request, and never got it. NEVER

**Comment by LieselGorlov** [comment]
I did not get anything from Vultr either.  🙈

**Comment by vikaspotluri123** [comment]
Gonna go ahead and close this since there seems to be issues with it

**Pull request closed without merging**
