### PR TITLE
Add Google Assistant

### PR DESCRIPTION
**Pull request by HarrisJT**
Couldn't find an image, but still worth listing.

### CODE REVIEW

**Comment by swapagarwal** [comment]
Thanks @HarrisJT! 👍

**Comment by swapagarwal** [comment]
I removed the $200 credits part as it isn't a tangible form of swag. What do you think?

**Comment by swapagarwal** [comment]
Continued in #3

**Comment by HarrisJT** [comment]
I wasn't sure so I put it in parenthesis, up to you. I would take 200$ of US Government swag ;)

**Pull request merged**
