### PR TITLE
added dx heroes swag opportunity

### PR DESCRIPTION
**Pull request by yogeshsingh101200**
- [x] I've checked that this isn't a new swag opportunity proposal.
- [x] I've checked that this isn't a duplicate pull request.

Added swag opportunity from DX Heroes

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
@aslafy-z same here, it doesn't seem like the opportunity offers swag for everyone that meets certain criteria

**Comment by yogeshsingh101200** [comment]
@aslafy-z @vikaspotluri123 should I close the pull request then?

**Comment by vikaspotluri123** [comment]
@yogeshsingh101200 just waiting on a consensus from @aslafy-z before making a decision

**Comment by yogeshsingh101200** [comment]
@vikaspotluri123 okay.

**Pull request closed without merging**
