### PR TITLE
Add WhatIsMyBrowser.com swag

### PR DESCRIPTION
**Pull request by aslafy-z**
Following up #32

### CODE REVIEW

**Comment by aslafy-z** [comment]
@swapagarwal: the other as been closed and is missing data now, that's why I opened a follow up PR

**Comment by aslafy-z** [comment]
`duplicate` label can be deleted.

**Comment by swapagarwal** [comment]
The difficulty circle has shrunk: https://shrinktheweb.snapito.io/v2/webshot/spu-ea68c8-ogi2-3cwn3bmfojjlb56e?size=800x0&screen=1024x768&url=https%3A%2F%2Fdeploy-preview-58--peaceful-chandrasekhar-efde8e.netlify.com%2F

**Comment by swapagarwal** [comment]
Thanks @aslafy-z! 👍

**Pull request merged**
