### PR TITLE
Seperate Active and Inactive Promotions

### PR DESCRIPTION
**Pull request by kevin51jiang**
For people who want to filter out inactive promotions.

Hacktoberfest website says "Check back next October for details on how to participate!" so I marked it as inactive.

### CODE REVIEW

**Comment by jgierer12** [comment]
Perhaps those could be wrapped in a `<details>` tag or put into a separate file to clean up the readme a bit. I imagine it will get quite cluttered once more things are added.

**Comment by swapagarwal** [comment]
Maybe we can add a badge similar to Digital Ocean?

@kevin51jiang @jgierer12 @pkalemba What do you think? 😄

**Comment by d4nyll** [comment]
My $0.02 - most of the time, visitors to the page wants to know opportunities they can enter _now_; having separated sections is going to make the page easier to scan through than having a badge.

**Comment by kevin51jiang** [comment]
This might seem a bit too complicated, but could we turn promos into seperate Json or text files or something, and make a directory to put them in? These files would have spots for tags, image url, status etc. Then get an app to run daily that will construct 3 different .md files. One for all, one in progress, and one for ended promos.

**Comment by rbstrachan** [comment]
I find this slightly pointless given that `Oktoberfest` is the only link that would be separated. This feature would come in handy if the list of inactive promotions was substantial so that the active promotions could be seen without constant interruption.
On top of that, it is made clear both in the title and the description that the promotion only runs in October, so labelling it `Inactive` also seems pointless.
Considerably changing the layout of the README for one link may actually make it more obtrusive and unintuitive to the user, rather than helping them read it, however, this is just my opinion.

**Comment by antonio6643** [comment]
Perhaps if more time-based promotions are added, we could add an "Upcoming Promotions" section.

**Comment by swapagarwal** [comment]
All promotions are currently active! 😇

**Pull request closed without merging**
