### PR TITLE
npm repo is archived and moved to a new repo, npm/cli

### PR DESCRIPTION
**Pull request by azkarmoulana**
npm has already archived their npm repository and moved to a new repository, https://github.com/npm/cli

### CODE REVIEW

**Comment by azkarmoulana** [comment]
@cozyplanes thanks for notifying

**Comment by swapagarwal** [comment]
Hey @azkarmoulana, can you rebase this?

**Comment by azkarmoulana** [comment]
@swapagarwal resolved the conflicts

**Comment by swapagarwal** [comment]
Sync the fork and you'll find that this change should now be done in `data.json` 😅
https://help.github.com/articles/syncing-a-fork/

**Pull request closed without merging**
