### PR TITLE
🎨 A11y Improvements to Site

### PR DESCRIPTION
**Pull request by vikaspotluri123**
- [x] I've checked that this isn't a duplicate pull request.

Please describe your changes here: 
- Add text for screenreaders to describe swag difficulty
  - tested using VoiceOver in iOS 12
- Add alt text to images

~~I also cleaned up the linting issues in the gulpfile. If it creates merge conflicts I'll drop the commit 😄~~ Reverted in favor of #59

### CODE REVIEW

**Comment by aslafy-z** [comment]
PR #59 already lint the gulpfile. I think you could drop the commit, or i'm gona rebase it once this is merged.

**Comment by vikaspotluri123** [comment]
@aslafy-z I'll drop it, there's one thing different in that PR which I commented on

**Comment by vikaspotluri123** [comment]
Fixed, not sure how that happened 🙈

**Comment by vikaspotluri123** [comment]
@swapagarwal pls don't merge this yet, I've got some more improvements coming down the pipeline ⛏

**Comment by aslafy-z** [comment]
@vikaspotluri123 add `WIP:` prefix in the title ;)

**Comment by vikaspotluri123** [comment]
Thanks, @zac-garby @aslafy-z had a minor brain fart 💨

**Comment by vikaspotluri123** [comment]
I'll probably rebase within the next 12 hrs

**Comment by vikaspotluri123** [comment]
@swapagarwal rebased, let me know if there's anything else to be done 👌

**Comment by swapagarwal** [comment]
@vikaspotluri123 Can you rebase again? 😅

**Comment by vikaspotluri123** [comment]
Rebased + fixed contrast ratio issues. Beamer has some issues so the score isn't 100 anymore but w/o beamer it is 🙃

**Comment by swapagarwal** [comment]
Thanks @vikaspotluri123! 👍
By the way, where were you checking the scores?

**Comment by vikaspotluri123** [comment]
> By the way, where were you checking the scores?

[lighthouse](https://developers.google.com/web/tools/lighthouse/)

**Pull request merged**
