### PR TITLE
Update Microsoft's Hacktoberfest tshirt

### PR DESCRIPTION
**Pull request by hugovk**
From https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/

- [x] I've checked that this isn't a duplicate pull request.

Is it regarding a new swag proposal or something else?  

Something else

Please describe your changes here: 

This is the design of Microsoft's Hacktoberfest tshirt:

> # Our Hacktoberfest t-shirt design
>
> Ashley McNamara, Cloud Developer Advocate, co-creator of the popular Gopherize.me, and advocate for all things open source, graciously donated some time to design our Hacktoberfest-themed t-shirt – and we can’t wait to start sending it to participants. Drum roll, please… here’s the design:

image

https://open.microsoft.com/2018/09/30/join-hacktoberfest-2018-celebration-microsoft/

### CODE REVIEW

**Comment by kevin51jiang** [comment]
Looks good

**Comment by aslafy-z** [comment]
Please update the readme

**Comment by hugovk** [comment]
@aslafy-z What needs updating in the README?

**Comment by aslafy-z** [comment]
Haha, sorry my bad, the whole content moved this night to the website only  :D

**Comment by swapagarwal** [comment]
Thanks @hugovk! 👍

**Comment by aslafy-z** [comment]
Here's the t-shirt

medium_100214241-5b3a511147552164a50626b23a5cb707

**Comment by kevin51jiang** [comment]
Tbh we should probably start removing the octoberfest posts since we're a. Good halfway through November already

**Comment by vikaspotluri123** [comment]
> Tbh we should probably start removing the octoberfest posts since we're a good halfway through November already

Hacktoberfest swag was hidden in #156

**Pull request merged**
