### PR TITLE
Fixed Grammatical Error

### PR DESCRIPTION
**Pull request by saksham-git**
- [ ] I've checked that this isn't a new swag opportunity proposal.
- [ ] I've checked that this isn't a duplicate pull request.

### CODE REVIEW

**Comment by vikaspotluri123** [comment]
@aslafy-z I'm not sure about this one either 😖

**Comment by aslafy-z** [comment]
Is it better? If so we can tag it invalid and merge it anyway

**Comment by vikaspotluri123** [comment]
I think it's fine either way

**Comment by aslafy-z** [comment]
Sorry @saksham-git, but this is not a meaningful PR. There are 40+ issues to solve in this repo, feel free to ask to be assigned to one of those.

**Pull request closed without merging**
