### PR TITLE
Add Umbraco swag

### PR DESCRIPTION
**Pull request by aslafy-z**
* Company: Umbraco
* Reference URL: https://umbraco.com/blog/happy-hacktoberfest/

Q. Have you received swag from this? No
Q. How long did it take? unknown
Q. Does it ship worldwide? unknown

Can't find any details about the swag they send:

From [reference](https://umbraco.com/blog/happy-hacktoberfest/):
> This means that all the contributors will be listed by Github username in a dedicated blog post in November. But that’s not all. We will also be giving away some super exclusive Umbraco swag for Hacktoberfest to everybody who sends us a pull request during October that is accepted to be merged (even if we for some reason don’t get around to merging it during October 😉).

Potential swag:
- https://twitter.com/umbraco/status/1044185328947539968
- https://twitter.com/umbraco/status/1045242679574089729
- https://twitter.com/codecabin/status/1050779418354962435

Image:

### CODE REVIEW

**Comment by aslafy-z** [comment]
@swapagarwal way better like this, thanks !

**Comment by swapagarwal** [comment]
Empty image!

**Comment by aslafy-z** [comment]
Just found some pics (seen this in the reference article: "Why not show off your new Umbraco SWAG at an upcoming Umbraco meetup or festival?" so I dug it down):

https://twitter.com/codecabin/status/1050779418354962435

**Comment by aslafy-z** [comment]
Nevermind, I just added an image of an umbraco t-shirt.

**Comment by aslafy-z** [comment]
@swapagarwal ready to merge

**Comment by swapagarwal** [comment]
Can think of adding something like `validThru` key to automatically make these `inactive` in November..

**Comment by aslafy-z** [comment]
I should have squashed this, sorry.

**Pull request merged**
